config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'site#home'
  resources :projects do
    resources :entries
  end

  namespace :api do
    resources :projects, only: [:show, :index, :create]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project
  validates :hours, :minutes, numericality: true, presence: true
  validates :date, presence: true
  validates :project_id, presence: true

  validate :project_exists

  private

  def project_exists
    unless Project.find_by(id: project_id)
      errors.add(:project_id, 'does not exist')
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :projects
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :group
  has_many :entries

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: {maximum: 30}
  validates :name, format:{with: /\A[\w\s*]+\Z/}

  def self.last_created_projects(number)
    order(created_at: :desc).limit(number)
  end

  def total_hours
    hours = 0
    minutes = 0
    entries.each do | entry|
      hours += entry.hours
      minutes += entry.minutes
    end
    hours + (minutes / 60)
  end

  # def hours_jofre
  #   entries.inject(0) do |hours, entry|
  #     hours + entry.hours + entry.minutes / 60.0
  #   end.to_i
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :memberships
  has_many :memberships
  has_many :projects, through: :groups
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  # This skips the token authentication validation, so we can use curl or other
  # commands to POST data to our app.
  skip_before_action :verify_authenticity_token

  def index
    @projects = Project.all.includes(:entries)
  end

  def create
    @project = Project.create(project_params)
    render 'show'
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  # This would need to permit user, group, etc.
  # This has been simplified for demo purposes.
  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :authenticate_user!

  def index
    @project = current_user.projects.find params[:project_id]
    @entries = @project.entries
  end

  def new
    @project = current_user.projects.find params[:project_id]
    @entry = @project.entries.new
  end

  def create
    @project = current_user.projects.find params[:project_id]
    @entry = @project.entries.new entry_params

    if @entry.save
      redirect_to action: :index, controller: :entries, project_id: @project.id
    else
      render 'new'
    end
  end

  def edit
    @project = current_user.projects.find params[:project_id]
    @entry = @project.entries.find params[:id]
  end

  def update
    @project = current_user.projects.find params[:project_id]
    @entry = @project.entries.find params[:id]

    if @entry.update_attributes entry_params
      redirect_to action: :show, controller: :entries, project_id: @project.id, id: @entry.id
    else
      render 'edit'
    end
  end

  def destroy
    @project = current_user.projects.find params[:project_id]
    @entry = @project.entries.find params[:id]
    if @entry.destroy
      redirect_to action: :index
    else
      redirect_to :back
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!

  def index
    @projects = current_user.projects.last_created_projects(10)
    render 'no_projects' if @projects.empty?
  end

  def show
    @project = current_user.projects.find_by id: params[:id]
    render 'no_project_found' unless @project
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message
    flash.keys.map do |key|
      message_div(key)
    end.join.html_safe
  end

  private

  def message_div(type)
    content_tag :div, class: 'message ' + type.to_s do
      content_tag :p do
        flash[type]
      end
    end
  end
end

app/views/entries/_entry_list_element.html.erb
<li>
  <%= entry_list_element.hours %> h
  <%= entry_list_element.minutes %> m -
  <%= entry_list_element.date %> -
  <%= link_to('Edit', edit_project_entry_path(@project, entry_list_element)) %>
  <%= link_to('Destroy', project_entry_path(@project, entry_list_element), method: :delete, data: { confirm: 'Segur?' }) %>
</li>

app/views/entries/_form.html.erb
<% if @entry.errors.any? %>
    <ul>
        <% @entry.errors.full_messages.each do |error_msg| %>
            <li><%= error_msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
    <%= f.label :hours %>
    <%= f.text_field :hours, size: 4 %>
    <br/>
    <%= f.label :minutes %>
    <%= f.text_field :minutes, size: 4 %>
    <br/>
    <%= f.label :date %>
    <%= f.text_field :date,  size: 4 %>
    <br/>

    <%= f.submit 'Save' %>
<% end %>

<%= link_to('Cancel', project_entries_path(@project)) %>

app/views/entries/edit.html.erb
<%= render 'form' %>

app/views/entries/index.html.erb
<h1><%= @project.name %></h1>
<%= flash_message %>
<ul>
  <% @entries.each do |entry| %>
    <%= render 'entry_list_element', entry_list_element: entry %>
  <% end %>
</ul>
<%= link_to('Go back', projects_path) %>
<br/>
<%= link_to('New entry', new_project_entry_path(@project)) %>

app/views/entries/new.html.erb
<%=render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project| %>
    <li>
      <%= project.name %>
      <% if project.description.present? %>
       - <%= project.description %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/projects/no_project_found.html.erb
<h1>
  Project not found with id: <%= params[:id] %>
</h1>

app/views/projects/no_projects.html.erb
<h1>
  No projects found
</h1>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<p>
<%= @project.description %>
</p>

<p><strong>Hours:</strong> <%= @project.total_hours %> </p>

app/views/site/contact.html.erb
<p>contact@example.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>

<p>Ironhack powered</p>